CREATE DATABASE CINEMA
USE CINEMA

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
ROOMNAME NVARCHAR(50)NOT NULL,
CHAIRNUMBER INT NOT NULL,
MOVIEID INT FOREIGN KEY REFERENCES MOVIES(ID), 
)

CREATE TABLE MOVIES(
ID INT PRIMARY KEY IDENTITY,
MOVIENAME NVARCHAR(50) NOT NULL,
MOVIEPRICE INT NOT NULL,
STARTDATE TIME(0) NOT NULL,
ENDDATE TIME(0) NOT NULL)

CREATE TABLE TICKETS(
ID INT PRIMARY KEY IDENTITY,
MOVIESID INT FOREIGN KEY REFERENCES MOVIES(ID),
ROOMSID INT FOREIGN KEY REFERENCES ROOMS(ID)
)

SELECT * FROM us_CinemaTickets
SELECT TICKET FROM us_CinemaTickets
SELECT  DBO.GETTICKETCOUNTS(1), DBO.GETTICKETCOUNTS(7), DBO.GETTICKETCOUNTS(4)
